export const MSG_SUCCESS = "MSG_SUCCESS";
export const MSG_SEND_SUCCESS = "MSG_UPDATE";

export const FRIEND_SUCCESS = "FRIEND_SUCCESS";

export const SOCKET_MESSAGE_SEND = "SOCKET_MESSAGE_SEND";
export const UPDATE_FRIEND_MESSAGE = "UPDATE_FRIEND_MESSAGE";
export const CLEAR_MESSAGE_SEND_SUCCESS = "CLEAR_MESSAGE_SEND_SUCCESS";

export const CLEAR_MESSAGE_GET_SUCCESS = "CLEAR_MESSAGE_GET_SUCCESS";

export const SEEN_MESSAGE = "SEEN_MESSAGE";

export const UPDATE = "UPDATE";
export const UPDATE_ALL = "UPDATE_ALL";

export const SEEN_ALL = "SEEN_ALL";

export const DELIVERED_MESSAGE = "DELIVERED_MESSAGE";
