export const CREATE_ACTION_TYPES = {
  ADD_IMAGES: "ADD_IMAGES",
  REMOVE_IMAGES: "REMOVE_IMAGES",
  ADD_INPUTS: " ADD_INPUTS",
  ADD_STATUS: "ADD_STATUS",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  ADD_DESC: "ADD_DESC",
  ADD_CAT: "ADD_CAT",
  ADD_SUB_CAT: "ADD_SUB_CAT",
  ADD_SHIPPING: "ADD_SHIPPING",
  ADD_USERID: "ADD_USERID",
  RESET_ITEMS: "RESET_ITEMS",
};
